Update animals.yml
Mira-Sector/space-station-14 pull request #167
Opened 2024-12-12 13:48 UTC by Sinis-Boop

Update Animals.yml design doc:

Added component "CanEnterPipeCrawling" Which, in this case, gives the mob in question (id: MobDianoNymph) the ability to crawl in vents and pipes.

Why:
Diano Nymphs are small, just like mice, geras, and mothroaches, so I think nymphs should be able to vent crawl too.

Balance: Diona Nymphs are incapable of doing anything on their own as a Nymph, which makes it very balanced for them to be able to move (pretty much) everywhere across the station. Turning into a nymph comes at a great cost of losing everything, including identity, so I think it's a fair trade off.

Gwen did NOT kidnap me and force me to change this line of code and i am not in need of any immediate rescue.

:3

2024-12-12 13:52 UTC, Doctor-Cpu requested changes
:trollface:

2024-12-12 13:52 UTC, Doctor-Cpu commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +  drawdepth: Mobs
indentation
needs one more tab so its under sprite

2024-12-12 13:52 UTC, Doctor-Cpu commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +  - type: CanEnterPipeCrawling
move this down to like the bottom of this idk

2024-12-18 14:26 UTC, Sinis-Boop commented
> :trollface:
:trollface:

2024-12-18 22:32 UTC, closed without merging